name: Android Build

on: pull_request

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: Set up JDK
        uses : actions/setup-java@v1
        with:
          java-version: '1.8'

      - name: Run Tests
        working-directory: ./app/src/
        run: chmod +x ./gradlew test


      - name: Build Project
        run: chmod +x ./gradlew assemble
